function BlocOd=omegdiif_DrDave(omeg,LenX,LenY)
BlocOd=zeros(LenX,LenY);
for dispX=-1:1
    for dispY=-1:1
        if (dispX==0) && (dispY==0)
            continue
        end
        BlocOd(max(1-dispY,1):(end-max(dispY,0)), max(1-dispX,1):(end-max(dispX,0))) = ...
            BlocOd(max(1-dispY,1):(end-max(dispY,0)), ...
            max(1-dispX,1):(end-max(dispX,0))) + ...
            abs(omeg(max(1-dispY,1):(end-max(dispY,0)), ...
            max(1-dispX,1):(end-max(dispX,0))) - ...
            omeg(max(1+dispY,1):(end+min(dispY,0)), ...
            max(1+dispX,1):(end+min(dispX,0))));
    end
end

end